variables:
  sandboxAzureSubscription: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
  acrName: mtcdensandboxdemo
  dockerNamespace: $(acrName).azurecr.io
  dockerRepository: msus-demos/demo-ruby-webapp
  imageName: $(dockerNamespace)/$(dockerRepository)
  storageAccountName: 

stages:
- stage: Build
  displayName: Build and Test the application
  jobs:
  - template: src/demo-ruby-webapp/azure-pipelines.yml
    parameters:
      azureSubscription: $(sandboxAzureSubscription)
      acrName: $(acrName)
      repositoryName: $(repositoryName)
      
- stage: Release
  condition: ne($(Build.Reason), "PullRequest")
  jobs:
  - deployment: Sandbox
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'Sandbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/terraform.yml
            parameters: 
              azureSubscription: $(sandboxAzureSubscription)
              storageAccessKey: $(storageAccessKey)
              storageAccountName: $(storageAccountName)
              environment: Sandbox
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(sandboxAzureSubscription)
              appType: 'webAppLinux'
              WebAppName: 'mtcden-demo-webapp-ruby-staging-app'
              DockerNamespace: $(dockerNamespace)
              DockerRepository: $(dockerRepository)
              DockerImageTag: $(build.buildId)
