trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - terraform/*

pr:
  autoCancel: true
 
variables:
  sandboxAzureSubscription: 'MTC Denver Sandbox'
  productionAzureSubscription: 'MTC Denver Production'
  storageAccountName: mtcdenterraformsandbox

# Build and Test
stages:
- stage: Verify
  jobs:
  - job: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        terraform fmt -check=true -diff=true
      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
      displayName: Verity the Terraform template format
      condition: eq(variables['Build.Reason'], 'PullRequest')

- stage: Staging
  jobs:
  - template: terraform/azure-pipelines.yml
    parameters:
      storageAccountName: mtcdenterraformsandbox
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(sandboxAzureSubscription)
      environment: staging

- stage: Production
  jobs:
  - template: terraform/azure-pipelines.yml
    parameters:
      storageAccountName: mtcdenterraformsandbox
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(productionAzureSubscription)
      environment: production