variables:
  sandboxAzureSubscription: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
  productionAzureSubscription: 'MTC Denver Production (72f988bf-86f1-41af-91ab-2d7cd011db47)'
  acrName: mtcdensandboxdemo
  dockerNamespace: $(acrName).azurecr.io
  dockerImageName: msus-demos/demo-ruby-webapp
  webAppName: 'mtcden-demo-webapp-ruby-sandbox-app'
  storageAccountName: 

stages:
- stage: Build
  jobs:
  - template: src/demo-ruby-webapp/azure-pipelines.yml
    parameters:
      azureSubscription: $(sandboxAzureSubscription)
      acrName: $(acrName)
      dockerFullyQualifiedImageName: $(dockerNamespace)/$(dockerImageName)
      dockerTag: $(Build.BuildNumber)

- stage: Staging
  jobs:
  - job: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Web App
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(sandboxAzureSubscription)
        appType: 'webAppContainer'
        WebAppName: $(webAppName)
        DockerNamespace: $(dockerNamespace)
        DockerRepository: $(dockerImageName)
        DockerImageTag: $(Build.BuildNumber)
        
# - stage: Production
#   jobs:
#   - job: Deploy
#     pool:
#       vmImage: 'Ubuntu-16.04'
#     steps:
#     - task: AzureRmWebAppDeployment@4
#       inputs:
#         ConnectionType: 'AzureRM'
#         azureSubscription: $(sandboxAzureSubscription)
#         appType: 'webAppContainer'
#         WebAppName: 'mtcden-demo-webapp-ruby-sandbox-app'
#         containerregistrytype:
#         DockerNamespace: $(dockerNamespace)
#         DockerRepository: $(dockerRepository)
#         DockerImageTag: $(Build.BuildNumber)