parameters:
  azureSubscription:
  acrName:
  dockerRepository:

jobs:
- job: BuildAndTest

  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    dockerImageTag: ${{ parameters['dockerRepository'] }}:${{ variables['Build.BuildId'] }}
    latestDevTag: ${{ parameters['dockerRepository'] }}:dev-latest

  steps:
  - task: AzureCLI@1
    displayName: Log in to ACR and pull latest dev image
    inputs:
      azureSubscription: ${{ parameters['azureSubscription'] }}
      scriptLocation: inlineScript
      inlineScript: |
        set -x
        az acr login -n ${{ parameters['acrName'] }}
        docker pull ${{ variables['latestDevTag'] }}
    
  - script: | 
      set -e -x
      docker build -t $(dev-latest) --target dev --cache-from ${{ variables['latestDevTag'] }} .
      docker run -e 'RAILS_ENV=test' dev bundle exec rspec
    displayName: Build dev container image and run tests

  - script: |
      set -e -x
      docker build --target release -t ${{ variables['dockerImageTag'] }} --cache-from ${{ variables['latestDevTag'] }} .
      docker push ${{ variables['dockerImageTag'] }}
      docker push ${{ variables['latestDevTag'] }}
    displayName: Build and push the release container image
    condition: ne(variables['Build.Reason'], 'PullRequest')
