parameters:
  azureSubscription:
  acrName:
  imageName:

jobs:
- job: BuildAndTest

  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    imageName: ${{ parameters['imageName'] }}:${{ variables['Build.BuildId'] }}
    devLatest: ${{ parameters['imageName'] }}:dev-latest

  steps:
  - task: AzureCLI@1
    displayName: Log in to ACR and pull latest dev image
    inputs:
      azureSubscription: ${{ parameters['azureSubscription'] }}
      scriptLocation: inlineScript
      inlineScript: |
        az acr login -n ${{ parameters['acrName'] }}
        docker pull ${{ variables['devLatest'] }}
    
  - script: | 
      set -e 
      docker build -t $(dev-latest) --target dev --cache-from ${{ variables['devLatest'] }} .
      docker run -e 'RAILS_ENV=test' dev bundle exec rspec
    displayName: Build dev container image and run tests

  - script: |
      set -e 
      docker build --target release -t ${{ variables['imageName'] }} --cache-from ${{ variables['devLatest'] }} .
      docker push ${{ variables['imageName'] }}
      docker push ${{ variables['devLatest'] }}
    displayName: Build and push the release container image
    condition: ne(variables['Build.Reason'], 'PullRequest')
