parameters:
  azureSubscription:
  acrName:
  dockerFullyQualifiedImageName:
  dockerTag:

jobs:
- job: BuildAndTest
  displayName: Build and Test
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    dockerImageAndTag: ${{ parameters['dockerFullyQualifiedImageName'] }}:${{ parameters['dockerTag'] }}
    latestBaseTag: ${{ parameters['dockerFullyQualifiedImageName'] }}:base-latest
    latestTestTag: ${{ parameters['dockerFullyQualifiedImageName'] }}:test-latest

  steps:

  # Build intermediate images
  - task: AzureCLI@1
    displayName: Log in to ACR, pull, build, and cache intermediate image
    inputs:
      azureSubscription: ${{ parameters['azureSubscription'] }}
      scriptLocation: inlineScript
      workingDirectory: $(System.DefaultWorkingDirectory)/src/demo-ruby-webapp/
      inlineScript: |
        # Log in to the Azure Container Registry
        az acr login -n ${{ parameters['acrName'] }}

        # Pull the latest Base image _if_ it's available, we'll use that as a cache later
        docker pull $(latestBaseTag) || true

        # Build the Base stage and tag it as the latest Base image
        docker build \
          -t $(latestBaseTag) \
          --target base \
          --cache-from $(latestBaseTag) \
          .

  # Run tests
  - script: | 
      # Fail on errors, output every command and result to the log
      set -e -x

      # Pull the latest Test image _if_ it's available, we'll use that as a cache later
      docker pull $(latestTestTag) || true

      # Build the Test stage and tag it as the latest Base image
      docker build \
        -t $(latestTestTag) \
        --target test \
        --cache-from $(latestBaseTag) \
        --cache-from $(latestTestTag) \
        .

      # Run RSpec tests
      docker run \
        -e 'RAILS_ENV=test' \
        $(latestTestTag) \
        bundle exec rspec -format RspecJunitFormatter --out result.xml

      # Push latest test image to ACR as test-latest
      docker push $(latestTestTag)
    workingDirectory: $(System.DefaultWorkingDirectory)/src/demo-ruby-webapp/
    displayName: Run RSpec Tests
    condition: eq(variables['Build.Reason'], 'PullRequest')

  # Build release container
  - script: |
      # Fail on errors, output every command and result to the log
      set -e -x

      docker build \
        -t $(dockerImageAndTag) \
        --target release \
        --cache-from $(latestBaseTag) \
        .

      # Build the Release Docker Stage, using the latest test image as a layer cache
      docker build \
        -t $(dockerImageAndTag) \
        --target release \
        --cache-from $(latestBaseTag) \
        .

      # Push the Release image to ACR
      docker push $(dockerImageAndTag)

      # Push the Base image to ACR as base-latest
      docker push $(latestBaseTag)
    workingDirectory: $(System.DefaultWorkingDirectory)/src/demo-ruby-webapp/
    displayName: Build and push the final container images
    condition: ne(variables['Build.Reason'], 'PullRequest')
