parameters:
  azureSubscription:
  acrName:
  dockerRepository:

jobs:
- job: BuildAndTest

  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    dockerImageTag: ${{ parameters['dockerRepository'] }}:$(Build.BuildNumber)
    latestDevTag: ${{ parameters['dockerRepository'] }}:dev-latest

  steps:
  - task: AzureCLI@1
    displayName: Log in to ACR and pull latest dev image
    inputs:
      azureSubscription: ${{ parameters['azureSubscription'] }}
      scriptLocation: inlineScript
      inlineScript: |
        set -e -x
        az acr login -n ${{ parameters['acrName'] }}
        docker pull $(latestDevTag) || true
    
  - script: | 
      set -e -x
      cd $(System.DefaultWorkingDirectory)/src/demo-ruby-webapp/
      docker build -t  $(latestDevTag) --target dev --cache-from $(latestDevTag) .
      docker run -e 'RAILS_ENV=test' $(latestDevTag) bundle exec rspec
    displayName: Build dev container image and run tests

  - script: |
      set -e -x
      cd $(System.DefaultWorkingDirectory)/src/demo-ruby-webapp/
      docker build -t $(dockerImageTag)  --target release --cache-from $(latestDevTag) .
      docker push $(dockerImageTag)
      docker push $(latestDevTag)
    displayName: Build and push the release container image
    condition: ne(variables['Build.Reason'], 'PullRequest')
