parameters:
  azureSubscription:
  storageAccountName:
  storageAccountKey:
  environment:
  planTier: standard
  planSku: s1

jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  # Terraform Deploy
  - task: AzureCLI@1
    displayName: Terraform Deploy
    inputs:
      azureSubscription: $(sandboxAzureSubscription)
      scriptLocation: inlineScript
      workingDirectory: $(System.DefaultWorkingDirectory)/src/terraform/
      arguments: '${{ parameters.storageAccountKey }}'
      inlineScript: |
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_SUBSCRIPTION_ID=$(az account show --query id)
        export ARM_TENANT_ID=$(az account show --query tenantId)

        terraform init \
            -backend-config="access_key=$1" \
            -backend-config="storage_account_name=${{ parameters['storageAccountName'] }}" \
            -input=false 

        terraform workspace select ${{ parameters.environment }} || terraform workspace new ${{ parameters.environment }}

        terraform plan \
          -var environment="${{ parameters.environment }}" \
          -var plan_tier="${{ parameters.planTier }}" \
          -var plan_sku="${{ parameters.planSku }}" \
          -out=${{ parameters.environment }}.tfplan \
          -input=false 
        
        terraform apply ${{ parameters.environment }}.tfplan
  condition: ne(variables['Build.Reason'], 'PullRequest')
