parameters:
  azureSubscription:
  storageAccountName:
  storageAccountKey:
  environment:
  planTier: standard
  planSku: s1

variables:
 environment: ${{ parameters['environment'] }}
 storageAccountName: ${{ parameters['StorageAccoutnName'] }}
 storageAccountKey: ${{ parameters['storageAccountKey'] }}
 planTier: ${{ parameters['planTier'] }}
 planSku: ${{ parameters['planSku'] }}

jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  # Terraform Deploy
  - task: AzureCLI@1
    displayName: Terraform Deploy
    inputs:
      azureSubscription: $(sandboxAzureSubscription)
      scriptLocation: inlineScript
      workingDirectory: $(System.DefaultWorkingDirectory)/src/terraform/
      arguments: '$(storageAccessKey)'
      inlineScript: |
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_SUBSCRIPTION_ID=$(az account show --query id)
        export ARM_TENANT_ID=$(az account show --query tenantId)

        terraform init \
            -backend-config="access_key=$1" \
            -backend-config="storage_account_name=$(storageAccountName)" \
            -input=false 

        terraform workspace select $(environment) || terraform workspace new $(environment)

        terraform plan \
          -var environment="$(environment)" \
          -var plan_tier="$(planTier)" \
          -var plan_sku="$(planSku)" \
          -out=$(environment).tfplan \
          -input=false 
        
        terraform apply $(environment).tfplan
  condition: ne(variables['Build.Reason'], 'PullRequest')
